spring:
  application:
    name: "SeekingLost API"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/seekinglost}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:190203}
    driver-class-name: com.mysql.cj.jdbc.Driver

aws:
  access-key: ${AWS_ACCESS_KEY:ASIAZBPGYG2GJSOPTTGE}
  secret-key: ${AWS_SECRET_KEY:nkNq4vESBlt1LblDq8CjBN5KJ1v2++ufU1703wMm}
  session-token: ${AWS_SESSION_TOKEN:IQoJb3JpZ2luX2VjEKv//////////wEaCXVzLXdlc3QtMiJGMEQCIB2SXpUOuHQ5j/dhrCkXKicYvqjPIIX4teytNyAQAPBOAiA7kCVLAD5DLzEP5jjC4GhgZgpC5yJVaXQpT/lrwh+iviq0Agjz//////////8BEAEaDDYyMTY0MzU3Njk3MiIMFaVwM6M68a83dq0MKogCb+HPUKDJF/Z75aQg7Gp1FCaIN8w9Ci2jmjmBRcwepYuRrsWmqbIAAQx/q7tnakxLwBEMDdQqJhRmjK8KXO4ZtR46xikyWerb6nV6QCU/xrAYg3g+eMa/ML0UJvEsCRuoHe/I3Uvlj5+8kMAb3/gwnS1/LFefcixKCs6kODHSylPt2QL98XiFX85hniwlglcwNSecf0Ua1od6pf92fT4iCd2eRWqVAI882LK1Rdr+OEyxVGTkHE9s4ajberket5sheW5XpHbskXexVd41syPutZg35fFxW99d1oUUu1yIi9E0qJTt3zjIMEV1LOwzJ0xev7W6oZXdsdpA1uaTJnzInD3F9eiPFdl8MK6murEGOp4BZVsoLiHRn6ctp2fcymH8x57UNjyie/ZWxujzSD6aStX//5OLwPP5ZXiEJE8ZGOMXV0PSprQvUpvJh4HJYzBxM+nGfCTCqDSvbgTYiEnDNUaHly8q3t1oxDt8yCJyIklSth7FaHzMo/zf4pdAQ4C9dMtv/YqEqPP3HJyhJXcbSa+UsPCeyP97xcXl1i+LyN3zBIi+EqycJ46f+2xqr50=}
  region: ${AWS_REGION:us-east-1}
  bucket-name: ${AWS_BUCKET_NAME:seekinglost-dados-treino-raw}